language: node_js

node_js:
  - lts/*

install: npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint
#  - npm run build
#  - npm run predeploy
  - npm run deploy

deploy:
  provider: pages
#  edge: true
  skip_cleanup: true
  github_token: $JOBNETZWERK_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: master

